[workspace]
members = [
	"midas",
	"cli",
	"linuxwrapper",
	"repl",
	"server"
]

[profile.dev]
opt-level = 0               # Use slightly better optimizations.
overflow-checks = true     # Disable integer overflow checks.