[package]
name = "debug_info"
version = "0.1.0"
edition = "2021"
test = false
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gimli = "*"
object = "*"
addr2line = "*"

[lib]
test = false
doctest = false